// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBREbuCViYKsZP1pT06VXC_FnlJQXBnJas',
    appId: '1:514684972130:web:79a44828ceeffb3aa9b53b',
    messagingSenderId: '514684972130',
    projectId: 'capstonefa23',
    authDomain: 'capstonefa23.firebaseapp.com',
    storageBucket: 'capstonefa23.appspot.com',
    measurementId: 'G-R9Y3KJ8P47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA4g3nd9nJQSPKDQYef5c_TE4AxEkIPR8',
    appId: '1:514684972130:android:d1a1f2985fa77fa4a9b53b',
    messagingSenderId: '514684972130',
    projectId: 'capstonefa23',
    storageBucket: 'capstonefa23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy28ICEEwUgAXrj92XxKdfdiP1FMp8-EM',
    appId: '1:514684972130:ios:ac033f8955da9671a9b53b',
    messagingSenderId: '514684972130',
    projectId: 'capstonefa23',
    storageBucket: 'capstonefa23.appspot.com',
    iosBundleId: 'com.example.capstoneFa23Driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy28ICEEwUgAXrj92XxKdfdiP1FMp8-EM',
    appId: '1:514684972130:ios:ed8e9d5c99104e9da9b53b',
    messagingSenderId: '514684972130',
    projectId: 'capstonefa23',
    storageBucket: 'capstonefa23.appspot.com',
    iosBundleId: 'com.example.capstoneFa23Driver.RunnerTests',
  );
}
